Fakulteti2/Controllers/ShfaqLendetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fakulteti2.Controllers
{
    public class ShfaqLendetController : Controller
    {
        // GET: ShfaqLendet
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fakulteti2/Controllers/ShfaqProfesoretController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fakulteti2.Controllers
{
    public class ShfaqProfesoretController : Controller
    {
        // GET: ShfaqProfesoret
        public ActionResult Index()
        {
           
            return View();
        }
    }
}

Fakulteti2/Controllers/ShtoLendetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fakulteti2.Controllers
{
    public class ShtoLendetController : Controller
    {
        // GET: ShtoLendet
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fakulteti2/Controllers/editController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fakulteti2.Controllers
{
    public class editController : Controller
    {
        // GET: edit
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fakulteti2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fakulteti", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                    <li>@Html.ActionLink("Shfaq Profesoret", "Index", "ShfaqProfesoret", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Shfaq Lendet", "Index", "ShfaqLendet", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Shto Profesor", "Index", "ShtoProfesor", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Shto Lendet", "Index", "ShtoLendet", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Ndrysho Profesoret", "Index", "edit", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fakulteti Aplikacioni</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>